### ISSUE TITLE
Working on Freeboard.io - never updates

### ISSUE THREAD

**Issue by benjaminchodroff** [alsm/freeboard-mqtt#3]
I am trying to get these plugins to work on the online freeboard.io but it doesn't seem to ever update. The way I did this was:
1. Create an account on freeboard.io, login
2. Create a new board
3. In the bottom right corner, click "Developer console"
4. Click the add button and add each of these, then click OK:
"https://raw.githubusercontent.com/alsm/freeboard-mqtt/master/paho.mqtt.plugin.js"
"https://raw.githubusercontent.com/alsm/freeboard-mqtt/master/ibm.iotfoundation.plugin.js"
5. Add a new datasource using the IBM IoT Foundation plugin:
Name: CloudOneIOTFoundation
Org: 5dj1dm
DeviceID: 78a5040fad88
API-Key: [obtained from IOT Foundation]
API Auth Token: [obtained from IOT Foundation]

That all looks great, but it never claims to update: "Last Updated: never"
Any ideas what I'm doing wrong? Do I also have to enter something into the MQTT client?

**Comment by alsm** [comment]
The two plugin files have a section that looks like this;

		"external_scripts" : [
			"<full address of the paho mqtt javascript client>"
		],

they don't have a direct link to a copy of the paho client, so you'd have to host the client code and the two plugins somewhere and edit them to point to the mqtt client.

**Comment by benjaminchodroff** [comment]
Appreciate the pointer!
Any chance we could default this to a publicly hosted (GitHub?) location?

I'll try to find this client and host it myself, but it would be very handy to have the default "just work"

Benjamin Chodroff
CTO
216-533-9272
benjamin.chodroff@oncloudone.com<mailto:benjamin.chodroff@oncloudone.com>



On Apr 30, 2015, at 09:43, Al S-M <notifications@github.com<mailto:notifications@github.com>> wrote:


The two plugin files have a section that looks like this;

    "external_scripts" : [
        "<full address of the paho mqtt javascript client>"
    ],


they don't have a direct link to a copy of the paho client, so you'd have to host the client code and the two plugins somewhere and edit them to point to the mqtt client.

**Comment by benjaminchodroff** [comment]
Al - Any chance you could take a look at what's going wrong? I placed the mqtt client in there (hosted in my github on https)

Here is my config:
https://github.com/benjaminchodroff/freeboard-mqtt/blob/paho-mqtt-default/ibm.iotfoundation.plugin.js

Firebug confirms the plugin is loaded, and it prints out a date stamp to the console, but then it times out while trying to do the client.connect(); I tried to debut the Paho mqtt javascript client but there is a lot going on in there that I don't understand. Does this plugin still work for you? Perhaps TLS connections are broken, or the mqttVersion needs to be explicitly set?

**Comment by benjaminchodroff** [comment]
Pretty sure I have root cause. IBM IoT Foundation isn't listening on port 8883 for SSL handshakes. The service appears broken. It appears most of the IBM example client libraries aren't actually implementing secure connections (they all list 1883??) so likely nobody in IBM is really testing how to do secure messaging. 

**Port 8883 is open:**
```
chodrofflaptop:~ benjamin.chodroff$ telnet 5dj1dm.messaging.internetofthings.ibmcloud.com 8883
Trying 23.246.232.210...
Connected to messaging.internetofthings.ibmcloud.com.
Escape character is '^]'.
```

**But SSL handshake fails:**
```
chodrofflaptop:~ benjamin.chodroff$ openssl s_client -showcerts -connect messaging.internetofthings.ibmcloud.com:8883
CONNECTED(00000003)
write:errno=54
```
**Compare that with a working version:**
```
openssl s_client -showcerts -connect test.mosquitto.org:8883
CONNECTED(00000003)
depth=1 /C=GB/ST=United Kingdom/L=Derby/O=Mosquitto/OU=CA/CN=mosquitto.org/emailAddress=roger@atchoo.org
verify error:num=19:self signed certificate in certificate chain
verify return:0
---
Certificate chain
 0 s:/C=GB/ST=United Kingdom/L=Derby/O=Mosquitto/OU=Public server/CN=test.mosquitto.org/emailAddress=roger@atchoo.org
   i:/C=GB/ST=United Kingdom/L=Derby/O=Mosquitto/OU=CA/CN=mosquitto.org/emailAddress=roger@atchoo.org
-----BEGIN CERTIFICATE-----
MIIDLTCCApYCCQCs9UdhbDFjdjANBgkqhkiG9w0BAQsFADCBkDELMAkGA1UEBhMC
R0IxFzAVBgNVBAgMDlVuaXRlZCBLaW5nZG9tMQ4wDAYDVQQHDAVEZXJieTESMBAG
A1UECgwJTW9zcXVpdHRvMQswCQYDVQQLDAJDQTEWMBQGA1UEAwwNbW9zcXVpdHRv
Lm9yZzEfMB0GCSqGSIb3DQEJARYQcm9nZXJAYXRjaG9vLm9yZzAeFw0xNTAxMDcy
MjU4MTlaFw0xOTEyMTIyMjU4MTlaMIGgMQswCQYDVQQGEwJHQjEXMBUGA1UECAwO
```

Thoughts? Help?? :)

**Comment by benjaminchodroff** [comment]
It turns out I was testing with an openssl client that didn't support TLS1.2 which is required by IOT foundation.

I found the bug within the code that is causing the connections to be rejected. The IOTF requires that the clientID be in the form 'a:orgID:whateveryouwant'. I changed your client line to look like this and it now works -- but there are other bugs:

var client = new Paho.MQTT.Client(currentSettings.org_id + '.messaging.internetofthings.ibmcloud.com',
8883, 'a:'+currentSettings.org_id+':'+currentSettings.api_key + (new Date().getTime()).toString());

Will keep working on it later and try to do a pull request. The other bugs I'm seeing are that device ID is required because I'm seeing socket disconnects if you try to just poll for all devices (and then freeboard does not try to connect again). Also, if it fails to connect, it gives up -- even if you try to manually refresh or change the settings. I'm getting closer -- and this code is a HUGE help. Thank you for it!

**Comment by alsm** [comment]
Glad it's helping you out :) If you're seeing disconnects from things you expect to work that is most likely due to the MQTT 3.1.1 standard of being unable to communicate access failures to the client so instead kills the connection after an "illegal" action. Interesting that you're having a problem with that though as I've used the "all device" connections before.
I have a hosted version of freeboard here http://freeboard.mybluemix.net/ adapted to use cloudant as a backend for storing the boards, I'd be interested to know if you have the same problems with your org details here.

**Comment by benjaminchodroff** [comment]
Definitely! The only real bug I’ve hit was the client device ID has to be in the form “a:<orgID>:whateveryouwant” — but the plugin code just used a random datestamp. Perhaps the IOTF changed their standards?

So far, the paho javascript client has been fairly rock solid *if* it connects successfully on the first attempt. If it fails for some reason, I have to refresh the page to make it attempt again. Haven’t traced back why it sometimes fails but I’m blaming spotty hotel wifi networks.

Here is my board. Nothing too interesting except when my device is online. I used rawgit.com to convert the plugin github.com account to serve the proper content-type headers.
https://freeboard.io/board/Rl1T1R

Thanks again!

Benjamin Chodroff
Chief Technology Officer
Mobile: +1-216-533-9272
Twitter: @benchodroff
benjamin.chodroff@oncloudone.com
[CloudOne]
www.oncloudone.com<http://oncloudone.com/> | <applewebdata://14D948E1-6605-4719-B186-3D5AA8523C15/www.doorsng.com> Free 60 Day Trial of DOORS NG<https://www.doorsng.com/>

From: Al S-M
Reply-To: alsm/freeboard-mqtt
Date: Tuesday, May 12, 2015 at 11:35
To: alsm/freeboard-mqtt
Cc: Benjamin Chodroff
Subject: Re: [freeboard-mqtt] Working on Freeboard.io - never updates (#3)


Glad it's helping you out :) If you're seeing disconnects from things you expect to work that is most likely due to the MQTT 3.1.1 standard of being unable to communicate access failures to the client so instead kills the connection after an "illegal" action. Interesting that you're having a problem with that though as I've used the "all device" connections before.
I have a hosted version of freeboard here http://freeboard.mybluemix.net/ adapted to use cloudant as a backend for storing the boards, I'd be interested to know if you have the same problems with your org details here.

**Comment by rajatksud** [comment]
I was not able to make this work on my installation so i tried to check out the freeboard installation on bluemix. This also is not working. I am able to see the values updating in MQTT Lens. Also I don't see the paho client connecting the apache-activemq server, where i can see the connected clients. It seems that the connection is not being made to the mqtt server. Any help will be appreciated.

**Comment by benjaminchodroff** [comment]
Here are the modified plugins that I loaded into the developer console of freeboard as plugins. Hope this helps.

https://rawgit.com/benjaminchodroff/freeboard-mqtt/paho-mqtt-default/ibm.iotfoundation.plugin.js
https://rawgit.com/benjaminchodroff/freeboard-mqtt/paho-mqtt-default/paho.mqtt.plugin.js

Benjamin Chodroff
Chief Technology Officer
Mobile: +1-216-533-9272
Twitter: @benchodroff
benjamin.chodroff@oncloudone.com
[CloudOne]
www.oncloudone.com<http://oncloudone.com/> | <applewebdata://14D948E1-6605-4719-B186-3D5AA8523C15/www.doorsng.com> Free 60 Day Trial of DOORS NG<https://www.doorsng.com/>

From: rajatksud
Reply-To: alsm/freeboard-mqtt
Date: Friday, September 4, 2015 at 10:59
To: alsm/freeboard-mqtt
Cc: Benjamin Chodroff
Subject: Re: [freeboard-mqtt] Working on Freeboard.io - never updates (#3)


I was not able to make this work on my installation so i tried to check out the freeboard installation on bluemix. This also is not working. I am able to see the values updating in MQTT Lens. Also I don't see the paho client connecting the apache-activemq server, where i can see the connected clients. It seems that the connection is not being made to the mqtt server. Any help will be appreciated.

**Comment by alsm** [comment]
Looks like this should be closed now with the merge :)
