### ISSUE TITLE
Multiple topic from single mqtt client

### ISSUE THREAD

**Issue by microspace** [alsm/freeboard-mqtt#4]
A remote controller publishes three topics to mosquitto broker: /board/temperature, /board/potentiometer, /board/soundlevel. 
In "the topic to subscribe to" I put "/board/#.
In gauge setting I wrote datasources["data"]["msg"]. Now all three topics are diplayed in the same guage and create. 
I want to display received data in three gauges. How to do this with creating single data source?
Thank you for your help.

**Comment by psorowka** [comment]
There are currently two possibilities to do that. 

### 1. Stay with a single data source and your subscription "/board/#"

Assuming your data source is called "BOARD"

In the particular widget settings, you can then open the JS editor and put: 

    if(datasources["BOARD"]["topic"].match(/temperature$/)) return datasources["BOARD"]["msg"]

so you will only display msgs from the "temperature" topic in this widget. 

### 2. setup one datasource for each topic

In this scenario you would add three distinct datasources and subscribe directly to /board/temperature 

Although this is a bit more userfriendly approach, this variant seemed to be not stable when loading a saved board.

**Comment by microspace** [comment]
Thank you! First possibility suits me.

**Comment by mrarmyant** [comment]
Sorry to bring up an old topic, the stability of a save board seems to be on reload.  I imagine if we slow down how quickly all the clients connect it might not be as janky.

**Comment by mrarmyant** [comment]
Sorry to bring up an old topic @, the stability of a save board seems to be on reload.  I imagine if we slow down how quickly all the clients connect it might not be as janky. 

I'm trying to get the first solution to work with no success :(  where is the documentation on .match() and why are there slashes and a dollar sign?


> There are currently two possibilities to do that.
> 
> ### 1. Stay with a single data source and your subscription "/board/#"
> Assuming your data source is called "BOARD"
> 
> In the particular widget settings, you can then open the JS editor and put:
> 
> ```
> if(datasources["BOARD"]["topic"].match(/temperature$/)) return datasources["BOARD"]["msg"]
> ```
> 
> so you will only display msgs from the "temperature" topic in this widget.
> 
> ### 2. setup one datasource for each topic
> In this scenario you would add three distinct datasources and subscribe directly to /board/temperature
> 
> Although this is a bit more userfriendly approach, this variant seemed to be not stable when loading a saved board.
