### ISSUE TITLE
Freeboard mqtt does not connect ever

### ISSUE THREAD

**Issue by wesselah** [alsm/freeboard-mqtt#5]
I am using the client and the plugin never connects.
i did some debugging with firebug and the message i get is 
Paho is not defined 
the script is stopped in firebug  when it hits this line: var client = new Paho.MQTT.Client(currentSettings.server

any idea?

**Comment by wesselah** [comment]
the message is gone now somehow the paha js was broken but the freeboard plugin still does not connect any idea?
checked everything over and over no strange behavoir with firebug but a connection is never made.
I am running the last freeboard version

**Comment by alsm** [comment]
From your first message I think the issue is that I do not distribute a copy of the Paho JS client that is required for this to work, you have to provide and edit your code to link to one of your own. Double check that the Paho client is being loaded correctly as that could still be your problem

**Comment by wesselah** [comment]
As you can see in my second comment That was indeed the issue but That was resolved and the js is Loaded with any problem.
But when i look at the wsmqtt.js i Loaded it still Does not work.i downloaded this ws js at eclipse but there seems to be a problem with it.
I followed several howto examples like this one https://primalcortex.wordpress.com/2015/02/25/setting-up-an-iot-frameworkdashboard-with-nodered-moscamosquitto-and-freeboard-io-dashboard/ which is very Well documenten but still the plug-in Does not work., when i use the hivemqtt webclient the ws js Works and connector. 
But unfortunatly i am not very Weel at js to troubleshoot. Any idea?

**Comment by alsm** [comment]
I'm sorry I can't think why it's not working for you, if I run through the example you linked to it all works.

**Comment by wesselah** [comment]
Okee thanks i wil look further

M.v.g. Albert

**Comment by jah-git** [comment]
Tonight I was working on the my freeboard with this plugin.  I was having the same issue. I discovered that with my mosquitto 1.4.5 on Ubuntu 14.04.03 that I needed to add {qos: 0} in the subscribe function call.  This fixed my issue.
Changed : (around line 92 -- I believe I have the "latest" code) 
		function onConnect() {
			console.log("Connected");
			client.subscribe(currentSettings.topic);
		};

to
		function onConnect() {
			console.log("Connected");
			client.subscribe(currentSettings.topic, {qos: 0});
		};
